### ISSUE TITLE
My account is not connecting with Mojang's Authenitcation Servers

### ISSUE THREAD

**Issue by furtabs** [BSDE-xSirBlockx/ACLauncher#35]
Hello, i am trying to use this launcher to connect to a server and it seems like i cant. I have bought minecraft and since **cracked launchers arent allowed** one would assume its an issue with your launcher. Mind explaining why i cannot connect to servers. Im clearly logged in and im pretty sure **this is ~~not~~ a cracked launcher** and if you mind looking into it.

**Comment by BSDE-xSirBlockx** [comment]
This is definitely not a cracked launcher, we authentificate with servers of mojang.
If you have problems login in, show us some screenshots so we can fix that.

This is definitely not a cracked launcher, why would we then build in a login?
